### ISSUE TITLE
数式を扱えるように

### ISSUE THREAD

**Issue by suzukin** [suzukin/tibooks-maker#10]
```
//texequation{
\sum_{i=1}^nf_n(x)
//}
```

に対応するために、PDFとEPUBで以下のstyとgemが必要であることが分かった（他にもあるかも）。次期パッケージで取り込みたい。
# latex
- wrapfig.sty (https://www.ctan.org/tex-archive/macros/latex/contrib/wrapfig)
- float.sty (https://www.ctan.org/tex-archive/macros/latex/contrib/float)
- geometry.sty (https://www.ctan.org/tex-archive/macros/latex/contrib/geometry)
# html
- math_ml (https://rubygems.org/gems/math_ml)

**Comment by suzukin** [comment]
実案件で拡張予定なのでお楽しみに！

**Comment by suzukin** [comment]
本家 https://github.com/kmuto/review/issues/773 でも、こちらでも似たようなところに落ち着きそう（EPUB側は画像化）。

**Comment by suzukin** [comment]
2.3.0で imgmath として追加されましたのでこちらはクローズしておきます。

**Comment by munepi** [comment]
@suzukin 
本題とそれていますが、コメントなさっておられたことに対して、回答いたします。

次期tibooks-makerでは、もう少し多くのLaTeXパッケージを追加しようと思います。

 * 現状のupstreamの標準な `layout_tex.erb` で必要とされる wrapfig.sty, float.sty, geometry.sty も自動的に追加されます。
 * 次の Re:VIEW MTG でやると思いますけれども、現状の `layout_tex.erb` がすでに大きすぎて、これで製作しているユーザさん、これを元に本来はLaTeXのバッドノウハウだけど、ググって入れてみて動けばOKなマクロを入れたりしているユーザさんもいらっしゃると思うので、そのような使い方もOKのままにしておくのが、ユーザさんの負担がないと思うんです。
