### ISSUE TITLE
グレースケール画像への自動変換の不備

### ISSUE THREAD

**Issue by suzukin** [suzukin/tibooks-maker#16]
https://github.com/thinkitcojp/tibooks-maker/blob/master/Makefile

```
images-tmpGrayscale:
    test ! -d images-tmpGrayscale
    echo Converting all images to grayscale ...
    cp -a images images-tmpGrayscale
    mogrify -type Grayscale images/*.*
    echo done.
```

この記述だと以下のように /images が階層構造をもつ場合に対応できないっぽい。

/images
-- /1_XXXX
-- /2_YYYY
-- /3_ZZZZ

**Comment by munepi** [comment]
`mogrify -type Grayscale images/*.*` の処理を `find images -type f` もしくは、特定の画像ファイルの拡張子を `find` にいくつか指定して与えて、images 以下の画像ファイルリストに対して、 `mogrify -type Grayscale ${i}` すればよさそうです。

**Comment by suzukin** [comment]
`find ./ -name "*.jpg" -o -name "*.png" | xargs mogrify -type Grayscale`
とりあえずこれで動いたっぽいです

**Comment by suzukin** [comment]
失敗。強制的に全画像グレースケール化されてしまった……。こちらでどうでしょうか。
`find images/ -name "*.jpg" -o -name "*.png" | xargs mogrify -type Grayscale`
