### ISSUE TITLE
indepimageの挙動がおかしい

### ISSUE THREAD

**Issue by suzukin** [suzukin/tibooks-maker#23]
`//indepimage[fig04016][マッピング]` の出力が、

`図5.1 図: マッピング` になってしまいます。

期待する出力は `図 マッピング` です。

**Comment by suzukin** [comment]
なお、indeptableの議論も進行中。
https://github.com/kmuto/review/issues/255

**Comment by munepi** [comment]
@suzukin 
私自身がまだ Re:VIEWの全タグを把握していないのですが、
この `//indepimage` の実装は、upstream側がad-hocです。

```
\newcommand{\reviewindepimagecaption}[1]{%
  \begin{center}#1\end{center}}
```

また、上記 kmuto/review#255 もひとまず ad-hoc な実装と言ってよいです。

これも別途実装が必要ですね。

**Comment by suzukin** [comment]
> また、上記 kmuto/review#255 もひとまず ad-hoc な実装と言ってよいです。
> これも別途実装が必要ですね。

そうですね、、拡張ツールであるtibooks-makerとしては、[リリースノート](https://github.com/kmuto/review/blob/master/NEWS.md)に表示されるようなNew Featuresに対しては追従して実装していく必要がありますね。。

**Comment by munepi** [comment]
> 拡張ツールであるtibooks-makerとしては、リリースノートに表示されるようなNew Featuresに対しては追従して実装していく必要がありますね。。

まさに、その話になりますね!!

武藤さんのこのつぶやき https://twitter.com/kmuto/status/911430268640047105 に対して、いろいろとつぶやきましたけれども、次期Re:VIEW MTGへの妄想 https://twitter.com/munepixyz/status/912153268129734656 
を思いつくまま下書きしております。

この「特定のクラスファイル」に相当するもののも、Re:VIEW upstream側にcommitして、tibooks-maker側も少ない実装になれば、嬉しいかなーと思います。

**Comment by suzukin** [comment]
> この「特定のクラスファイル」に相当するもののも、Re:VIEW upstream側にcommitして、tibooks-maker側も少ない実装になれば、嬉しいかなーと思います。

おお！ これが入るとRe:VEWがまた一段と使いやすくなりますねー
