### ISSUE TITLE
ボールド指定の欧文が明朝ゴシックになる

### ISSUE THREAD

**Issue by suzukin** [suzukin/tibooks-maker#24]
忘れないうちにいったんメモ

**Comment by munepi** [comment]
@suzukin 
これは、 `\textbf` の意味が単に「weight bold」とするからです。

 * 本文中の `\textbf` のフォント仕様を決める
 * 特定の要素の `\textbf` のフォント仕様を決める

など、特定のクラスファイルごとに、仕様を与えられます。

**Comment by suzukin** [comment]
@motoot えーとこれって何が問題なんでしたっけ？ すみません肝心なところを忘れてしまいました。。

**Comment by motoot** [comment]
日本語と欧文が混在したときに、見た目の問題で、美しくないからです。通常のDTPでは、デザイナーさんだと設定しないので。
クリティカルな問題ではないです。

寺内

2017/09/25 20:34、Noriyuki Suzuki <notifications@github.com>のメール:

**Comment by munepi** [comment]
@motoot 寺内さん、
ご無沙汰しております。

> 通常のDTPでは、デザイナーさんだと設定しないので。

こちらもそれを期待しているわけではございません。
それゆえ、本件を「バグ」として、Re:VIEW側の対応と必要に応じてLaTeX側の対応できればと存じます。

本件を再現例（できるかぎり最小なマークアップされた文章で本件を再現できるRe:VIEW文章.reファイル、本件を再現できる設定や環境などの（できるかぎり少ない）条件）を出していただけますと、双方ともにテストしやすいです。

@suzukin さん、
このissueも tibooks-maker 改修の項目に入れて良いですね？
本件はわたしが直前でコメントした推察どおりでした：

> これは、 \textbf の意味が単に「weight bold」とするからです。
>
> * 本文中の \textbf のフォント仕様を決める
> * 特定の要素の \textbf のフォント仕様を決める
> など、特定のクラスファイルごとに、仕様を与えられます。

本件の再現例をいただくとして…、

***

**Comment by munepi** [comment]
@suzukin さん、

いま、Re:VIEWの全タグを含むサンプルをupstream側に求めています。
https://twitter.com/munepixyz/status/912248621893955584

ThinkIT Books, ITLeaders選書は、ひとまず、Re:VIEW全タグを必要としていませんけれども、
現状の組版仕様で想定する全タグ（⊂Re:VIEW全タグ）の例サンプルは、作っておきたいと思います。

やはり、これがないと、変換器出力の検証がしづらくて、issueごとに場当たり対応になりがちです。
以前、itleaders-books対応した祭に、別途zipファイルに同梱してお送りした `test.re` などがGitHubにも上がっておりません。
それゆえ、別途issueを立てて、「現状の組版仕様で想定する全タグ（⊂Re:VIEW全タグ）のサンプル」を検討したほうが良さそうです。

**Comment by suzukin** [comment]
@munepi できればkmutoさんの全タグサンプルを待ちたいところです。
