### ISSUE TITLE
chapter:total-numberオプションオフでも付録のツメが表示される

### ISSUE THREAD

**Issue by suzukin** [suzukin/tibooks-maker#26]

**Comment by munepi** [comment]
@suzukin 
これは、例のDrupal8本のときのままですね。
ひとまず、付録ではツメが入らないにしようと思います。

**Comment by suzukin** [comment]
@munepi なんだかんだでツメは良い機能だと思うので、

* オプションオフでは付録にツメなし
* オプションオンでは付録にツメあり

がベストですが、難しそうでしたらデフォルトで付録にはツメなしでお願いできればと！

**Comment by munepi** [comment]
@suzukin 
>  * オプションオフでは付録にツメなし
>  * オプションオンでは付録にツメあり
> がベスト

かしこまりました。
