### ISSUE TITLE
nonum絡みのバグ？

### ISSUE THREAD

**Issue by suzukin** [suzukin/tibooks-maker#27]
* 見出しが右寄せになる
* 1つ前のブロックの柱が表示される

これは本家の問題だと思うのでサンプルを用意して報告しようかと思います。

**Comment by munepi** [comment]
@suzukin 
これの再現例はありますでしょうか？

**Comment by suzukin** [comment]
https://github.com/kmuto/review/pull/555
そもそも本家も認識済みでサポートしてない部分でした、採番ロジックを（EPUBも含めて）考えていくのは大変そうですね。。

**Comment by suzukin** [comment]
いったんクローズしておきます。

**Comment by munepi** [comment]
@suzukin 
一応、わたしのほうで本質的な問題の把握をさせてくださいませ。

**Comment by suzukin** [comment]
@munepi 
https://github.com/kmuto/review/issues/506
から流れを追っていただくのが良いかと思います。前回のdevelopers meeting（といっても1年半くらい前）から見出しの表示方法に関する議論があり、最終的に現在は3パターンのオプションが用意されています。
https://github.com/kmuto/review/blob/master/doc/format.ja.md#コラムなど

```
[nonum] : これを指定している章・節・項・段には連番を振りません。見出しは目次に含まれます。
[nodisp] : これを指定している章・節・項・段の見出しは変換結果には表示されず、連番も振りません。ただし、見出しは目次に含まれます。
[notoc] : これを指定している章・節・項・段には連番を振りません。見出しは目次に含まれません。
```
ただ、採番含めてEPUB/LaTeX両方で完全に対応できているとはいえない状況です。
