### ISSUE TITLE
High Sierra環境でのヒラギノフォント問題

### ISSUE THREAD

**Issue by suzukin** [suzukin/tibooks-maker#29]
パブリックプレビュー 10.13 Beta（17A291m）ですが、以下のワーニングが出てビルドが止まってしまう模様です。

```
dvipdfmx:warning: Could not locate a virtual/physical font for TFM "upaotffutogob101pr6n-b-h".
dvipdfmx:warning: >> This font is mapped to a physical font "HiraginoSansR-W4.ttc".
dvipdfmx:warning: >> Please check if kpathsea library can find this font: HiraginoSansR-W4.ttc
dvipdfmx:fatal: Cannot proceed without .vf or "physical" font for PDF output...
```

**Comment by munepi** [comment]
tibooks-makerでは、現状、和文フォントの従属欧文を使っておりませんから、欧文フォントは基本的にフリーフォントで事が足りています。

（ここは今後の特定のクラスファイルでその仕様を緩めてもよいかもしれません）

それゆえに、 `cameraready=preview` のときの和文フォントも、Mac OS Xだからといって、OS同梱のヒラギノフォントをわざわざ使うこともなく、高品質な源ノ明朝、源ノ角ゴシックで十分ですね。

（そうすると、もはや、tibooks-maker は…、OSの制限すら無くなります!!）
