### ISSUE TITLE
画像フォルダーとMakefileの再考

### ISSUE THREAD

**Issue by suzukin** [suzukin/tibooks-maker#31]
## 課題

 * オフセットないしPOD版PDFを作成するたびにグレースケール化処理（images-tmpGrayscale）が走るので画像100個とかになるとかなり待たされる

* （主にオフセット用途で）ちゃんと作ろうとすると自動化されたグレースケール画像（.png/.jpg）では使えない、解像度的にも .eps/.pdf になる

実運用を考えると /images とオフセット＆POD用のグレースケール画像フォルダーは分けて考えたほうが良さそう。

## 解決策？

* 旧仕様のシンボリックリンク形式に戻す
* images-tmpGrayscale コマンドはそのまま、スポットで変換処理を実行できるように
* ちなみに /images 決め打ち問題は本家仕様によるもの（https://github.com/kmuto/review/issues/447）

**Comment by munepi** [comment]
ここらへん、必要なPDF仕様（target）を整理する必要がありますね。
こちらもお手伝いいたします。

**Comment by suzukin** [comment]
はーい、現行のプロジェクトでひとまずテストしながら進めてます。

**Comment by suzukin** [comment]
@munepi 

画像フォルダーの件からはちょっと話がそれますが、PODの入稿仕様変更に伴い新たなPDF仕様として config-pod を設計しようと考えています。config-spからの変更点は以下の通りです。

* 仕上がりサイズに対して+3mmの塗り足し（ツメの塗り足し処理が必要になります）
※B5変型版（182 × 232mm）の場合は、仕上がりが182 × 232mmで、裁ち落としサイズ＝アートサイズが188 x 238mmとなります。

これは現状の `texdocumentclass` オプションで実現できるのでしょうか？

**Comment by munepi** [comment]
@suzukin 
（本日、メールの方も折り返しいたします m(_ _)m）

> これは現状の texdocumentclass オプションで実現できるのでしょうか？

それもすでに柔軟に対応できます。

 * 印刷仕様
 * 物理的なトンボなし、デジタルトンボあり
 * 裁ち落とし+3mmあり

ですから、以下の設定で実現可能です。

```
  cameraready=print,  paper=b5var+3mm
```

**Comment by suzukin** [comment]
@munepi 

>  cameraready=print,  paper=b5var+3mm

上記の設定だとアートサイズ（Acrobat上の赤線）が182 × 232mmのPDFが出力されませんか？ 実現したいのは仕上がりサイズ（TrimBox、Acrobat上の緑線）が182 × 232mmの状態のものです。以下のような感じです！

![2017-09-25 19 26 58](https://user-images.githubusercontent.com/5789999/30804215-85c0f480-a227-11e7-8ce8-9d27cec86cea.png)

**Comment by munepi** [comment]
@suzukin 
さっそくご返信をありがとうございます。

> TrimBox、Acrobat上の緑線

これでようやく分かりました!!
これをLaTeX内でやろうとすると、
別途 `cameraready=なんちゃらpod` みたいな特定の印刷デバイス向けを新設すると良いですね!

ひとまず、Acrobatなどで手動でご対応いただいて、次期tibooks-maker改修要件の一つとさせていただきたく存じます。

**Comment by munepi** [comment]
この場合、 `/ArtBox` も `/TrimBox` も同じ値で出しており、赤線と緑線が重なっていますね。
実際には、 `/ArtBox` が「PDF文章を画像として用いる場合における画像としての領域」ですから、あえて赤線を出す必要ないですね。それゆえ、 `/ArtBox` を明示的に出力しないことにいたします。

（このPage Box（ﾅﾝﾄｶBox）は、PDF仕様と各種ソフトウェアのPage Boxの振る舞いを理解していないとややこしいですね :D ）

**Comment by munepi** [comment]
@suzukin さん、
> 旧仕様のシンボリックリンク形式に戻す

のが現実的だと思います。

**Comment by munepi** [comment]
@suzukin さん、
tibooks-maker 2.3.0 で本件のMakefileの再検討が未完了だったと思います。

印刷版PDFをK版にするけれども、印刷用図版を別途作成しない場合、callas pdfToolbox Desktopを用いる前提であれば、

 1. Re:VIEW pdfmakerでLaTeX組版からPDFファイルを生成
 2. callas pdfToolboxでK版に変換
 3. callas pdfToolboxで印刷仕様（PDF/X-1a または PDF/X-4）に変換

の3ステップで、印刷版PDFを作成できます。
そして、上記、2, 3の処理を callas pdfToolbox では、1つのプロセスプラン（各アクションを1つにまとめる、バッチ処理）としてまとめられます。

（※もちろん、callas pdfToolbox Desktopを用いずに、Adobe Acrobat Proの「印刷工程」、「プリフライト」、「色変換」などを駆使すると、同等な処理ができますけれども、callas pdfToolbox ほど簡単にならないと思います。）

![2017-12-27 11 01 47](https://user-images.githubusercontent.com/583148/34368217-839d95b6-eaf5-11e7-9606-08633f568881.png)
![2017-12-27 11 00 32](https://user-images.githubusercontent.com/583148/34368219-85c7138a-eaf5-11e7-9cc9-01957ce62264.png)
![2017-12-27 11 02 51](https://user-images.githubusercontent.com/583148/34368220-879ae20e-eaf5-11e7-9524-c3f9c8a186c2.png)

そこで、現状、 `Makefile` 内でグレースケールに変換している処理をやめてしまい、単純にPDFファイルを生成することだけにしてしまったらいかがでしょうか？
