### ISSUE TITLE
アクセント付きラテン文字などの処理がうまくいかない

### ISSUE THREAD

**Issue by suzukin** [suzukin/tibooks-maker#32]
`Pokémon` を実現しようとすると、

![2017-08-17 18 25 45](https://user-images.githubusercontent.com/5789999/29405664-81c05adc-8379-11e7-981a-7ef89de17223.png)

こうなってしまう。これを回避するために、以下を参考に `pxcjkcatパッケージ` を読み込んで、

http://qiita.com/zr_tex8r/items/297154ca924749e62471#%E3%81%9D%E3%81%AE10uptex%E3%81%AE%E5%92%8C%E6%96%87%E3%82%AB%E3%83%86%E3%82%B4%E3%83%AA%E3%82%B3%E3%83%BC%E3%83%89%E3%81%8C%E3%82%A2%E3%83%AC

`\usepackage[prefernoncjk]{pxcjkcat}` したらこうなった。

![2017-08-29 23 00 54](https://user-images.githubusercontent.com/5789999/29824991-f4b58786-8d0d-11e7-8397-8ec54f0865c1.png)

試しにMacTeXでもう1つ環境を作ったらそちらはうまくいったので `tibooks-maker` 特有の問題と考えられる。

**Comment by munepi** [comment]
> 試しにMacTeXでもう1つ環境を作ったらそちらはうまくいったので tibooks-maker 特有の問題と考えられる。

いいえ、以下のtex文章において、任意の環境で本件を再現できます。

```latex
%#!ptex2pdf -l -u
\documentclass[uplatex]{jsarticle}\listfiles
%\documentclass{itleaders-books}
\usepackage[prefernoncjk]{pxcjkcat}[2012/09/22 v1.0]
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\begin{document}
Pokémon

20XX年X月X日にβ版として発売された
\end{document}
```

また、本件を突破しても、上記TeX文章内の「β」で以下のように言われます。

```
! Package inputenc Error: Unicode char β (U+3B2)
(inputenc)                not set up for use with LaTeX.
```

早い話、pxcjkcat.sty で丸っと和文以外の文字を「欧文扱い」としてしまうか、チマチマと \kcatcode で一つずつ欧文扱いにしていくかということです。

```latex
%#!ptex2pdf -l -u
\documentclass[uplatex]{jsarticle}\listfiles
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{lmodern}

\kcatcode`é=15

\begin{document}
Pokémon

20XX年X月X日にβ版として発売された
\end{document}
```

いずれの方法も、期待値通りにいかない例外のUnicodeに対して、一つずつ指示せざるを得ません。
それゆえ、

 * 既存の普通の日本語pTeX組版の方法：初めから「é」は通常のT1エンコーディングで `\'e` としてしまうのが一つ。Re:VIEWであれば、uplatexを実行する前処理で置換する。
 * とりあえずUTF-8の直入力を許容させておいて、例外対応していく方法： `\usepackage[utf8]{inputenc}` の下で、uptexに `\kcatcode`é=15` として「é」を欧文扱いするように教えてあげる。

個人的な経験上、アクセント付き文字たちは限られていることから、該当文字たちをエスケープしてしまって、T1エンコーディングの範囲で対処する方が、一貫性のある対応ができると思います。

**Comment by suzukin** [comment]
@munepi 調査ありがとうございます！

> 既存の普通の日本語pTeX組版の方法：初めから「é」は通常のT1エンコーディングで \'e としてしまうのが一つ。Re:VIEWであれば、uplatexを実行する前処理で置換する。

アドバイス通りこちらでいこうかと。具体的にはRe:VIEWの `@<raw>` で対応、EPUBもあるので表記としては以下で進めようと思います。

`@<raw>{|latex|\'e}@<raw>{|html|é}`

**Comment by munepi** [comment]
@suzukin 

> アドバイス通りこちらでいこうかと。具体的にはRe:VIEWの @<raw> で対応、EPUBもあるので表記としては以下で進めようと思います。
> 
> @<raw>{|latex|\'e}@<raw>{|html|é}

いいえ、EPUBに対しては何もしなくてOKです！！！
つまり、すべてのRe:VIEW原稿 *.reに対して、何もしなくてOKです！！！

こちらで、 `hook_beforetex.rb` でuplatex + dvipdfmx -> PDFのみに対応いたします！

**Comment by suzukin** [comment]
あ、もと原稿はいじらなくて hook_beforetex で対応とのこと承知しました！
[こっち](https://github.com/takahashim/g11nbook/issues/10)にもリンクしておきます。

**Comment by munepi** [comment]
該当プロジェクトでは、T1エンコーディングに落とすことで対処いたしましたけれども、 hook_beforetex.rb で対応することを前提としてしまいますゆえ、やはりUTF-8で直打ちしたまま対応できるように対処したいと思っております。

ひとまず、以下ぐらいで十分かなーと考えています。


``` latex
%#!ptex2pdf -l -u
\documentclass{ujarticle}
\usepackage[T1]{fontenc}\usepackage{textcomp}
\usepackage[utf8]{inputenc}

\usepackage[prefernoncjk]{pxcjkcat}
\cjkcategory{sym18,grek}{cjk}

\pagestyle{empty}
\begin{document}
Pokémon GO

\fontfamily{lmr}\selectfont
Pokémon GO

\fontfamily{lmss}\selectfont
Pokémon GO
\end{document}
```

**Comment by munepi** [comment]
その後、「★」なども必要になり、以下のように変更しております。

``` latex
\usepackage[utf8]{inputenc}
\usepackage[prefernoncjk]{pxcjkcat}
\cjkcategory{sym18,sym19,grek}{cjk}
```
