### ISSUE TITLE
Re:VIEW 2.4.0対応

### ISSUE THREAD

**Issue by munepi** [suzukin/tibooks-maker#36]
* [x] シンタックスハイライト：Rouge #37 
 * [x] 数式画像化（和文対応にしときますか？） #39 
    * Ghostscript, ImageMagickの同梱
 * [x] 各種 image-XXXXX -> images #35 #31 
 * [x] レイアウト layout.tex.erb の索引対応 #38

**Comment by munepi** [comment]
@suzukin さん、
遅ればせながら、 v2.4.0 対応した dmg を put しました。
https://github.com/thinkitcojp/tibooks-maker/releases/tag/v2.4.0rc1

**Comment by munepi** [comment]
fixed #36

**Comment by munepi** [comment]
close #36

**Comment by suzukin** [comment]
@munepi RC1の検証が遅くなってしまったのですが、以下の通り起動に失敗するようです。macはHigh Sierraです。

```
tibooks-maker-2.4.0-20180325

This is constructed from the following components:
 * Ruby:	ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin15]
   * Re:VIEW:	review (2.4.0, 2.3.0, 2.2.0, 2.1.0, 2.0.0)
   * md2review:	md2review (1.12.0)
 * TeX Live
   * uplatex:	e-upTeX 3.14159265-p3.7-u1.21-160201-2.6 (utf8.uptex) (TeX Live 2016)
   * dvipdfmx:	dvipdfmx Version 20160307 

[tibooks-maker]:tibooks-maker (master)$ gmake book.pdf
Illegal instruction: 4
```

**Comment by munepi** [comment]
@suzukin さん、
すみません、これは、例えば [docker/compose - Binary on darwin fails with "illegal instruction" on some machines](https://github.com/docker/compose/issues/271) などと同じですね。CPUセット命令をより汎用でビルドしないといけないですね。

**Comment by munepi** [comment]
@suzukin さん、

tibooks-maker-2.5.0-20180629 の公開として、対処いたしました。

https://github.com/thinkitcojp/tibooks-maker/releases/tag/v2.5.0


``` bash
$ gmake book.pdf
Illegal instruction: 4
```

このエラーに対して、tibooks-maker-2.4.0-20180325.dmgにおける ruby を含むバイナリが  `-march=native` でビルドされていました。

ibooks-maker の各種バイナリはHomebrewをベースにしていますが、Homebrew によるビルドは、基本的にビルドするマシンのCPUセットに最適化されてるようになっていて、その仕組みを回避して `-march=core2`  でビルドするようにしています（この仕組みがしばらくすると、また変わるかもしれませんが…）。

それゆえ、tibooks-maker-2.4.0-20180325.dmg を一旦削除し、同梱される各種バイナリを OS X 10.11 上で  `-march=core2` でビルドし、 Re:VIEW 2.5.0 に対応した tibooks-maker を公開します。

https://github.com/thinkitcojp/tibooks-maker/releases/tag/v2.5.0

現状の製作に必要となった、数式の画像化や rouge によるシンタックスハイライトのための各種ツールもすべて同梱いたしました。

**Comment by suzukin** [comment]
2.5.0の動作を確認できました、ありがとうございます！
