### ISSUE TITLE
EPUBの外部リンクを除去するオプションが欲しい

### ISSUE THREAD

**Issue by suzukin** [suzukin/tibooks-maker#6]
電書協の仕様で弾かれることがあるため回避しておきたい。
こっちで作って本家にパッチを送るのもあり。

参考
https://github.com/kmuto/review/issues/429

**Comment by munepi** [comment]
contents matter のため、config.yaml 内の `epubmaker:`で、適当な段階で hook するのが賢明だと思います。

**Comment by suzukin** [comment]
Re:VIEW2.0.0で機能追加されました！
https://github.com/kmuto/review/blob/master/doc/NEWS.ja.md#新機能
