### ISSUE TITLE
左起こしオプション

### ISSUE THREAD

**Issue by suzukin** [suzukin/tibooks-maker#8]
書籍的ではないもの（雑誌や小冊子）を作成する際に、openany, openleftの設定が欲しい。texdocumentclass に設定しても現状では動かない模様。

**Comment by suzukin** [comment]
追記。
現状はcatalog.ymlで設定した各種.reはすべて偶数ページになる設定がデフォルトで（奇数ページの場合は最後に自動的に白ページが差し込まれる）、必ず右起こしになる。これを回避するオプションが欲しいです。

**Comment by munepi** [comment]
LaTeX の標準的なクラスファイルにあるクラスオプション openany, openleft は、イマイチ使い勝手が悪いので、README-pdfmaker.mdにあるように各種直前改丁頁制御 `<selector>:break-before` を設けています。
thinkit-books, itleaders-books に対して、`part:break-before`, `chaper:break-before` を実装すれば、本 issue をみたすと存じます。

```
各種直前改丁頁制御：default: right; left, page
 * frontmatter:break-before=page
 * mainmatter:break-before=page
 * backmatter:break-before=page
 * appendix:break-before=page
 * toc:break-before=page
 * idx:break-before=page
```

**Comment by suzukin** [comment]
なるほどよく考えられたオプションですね！ ただ確かに直前の白ページの制御には効きそうですが、ノンブルと柱の位置も連動させるにはどうすべきでしょうか。。試しに `mainmatter:break-before=page,` を設定して本章直前（目次直後）の白を削除し第1章を左起こしにしたのですが、ノンブルと柱は追従しませんでした（左右の位置がちぐはぐになる）。サンプルを添付します。
[book.pdf](https://github.com/thinkitcojp/tibooks-maker/files/178062/book.pdf)

**Comment by munepi** [comment]
thinkit-books や itleaders-books のような前付けのノンブルが roman、本文以降のノンブルが arabic の書籍構造では、mainmatter:break-before を初期値 right（右おこし）以外にする意味がありません。
なぜならば、前付けが右頁（奇数）で終わった場合、本文1頁目が左頁（ノンブルが 1：奇数）となり、本文以降の奇数ノンブルが左頁となってしまいますが、それは実際に書籍構造として存在しません。
したがいまして、実際に mainmatter:break-before が page であるような書籍は、前付け以降のノンブルがすべて arabic である場合にかぎります。

**Comment by suzukin** [comment]
書籍的ではないということでいったんクローズします。柱をなくしてノンブルを中央寄せにすれば回避できるかな。

**Comment by suzukin** [comment]
itleaders-books が章の左起こしに対応してた
