### ISSUE TITLE
apostropheとbacktickの扱い

### ISSUE THREAD

**Issue by suzukin** [suzukin/tibooks-maker#9]
「`」が「’」に変換されてしまう
「'」が「’」に変換されてしまう

**Comment by suzukin** [comment]
https://github.com/thinkitcojp/tibooks-maker/issues/10 と要調整。list内はモトイキがよさげ。

**Comment by suzukin** [comment]
これ確かなおしてもらった気がするのでクローズします。

**Comment by munepi** [comment]
できうるかぎり賢明な対応にしたいので、次のtibooks-makerで、こちらにさらに手をいれます。
